id: I4CEF73EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:04:40+00:00'
last_modified: '2022-06-08T16:13:38.064485+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29339
  title: བྱང་གཏེར་འདོན་ཆའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8EDD:
      image_group_id: I5273
      title: ''
      total_pages: 1520
      order: 1
      base_file: 8EDD.txt
    5F7D:
      image_group_id: I1KG15264
      title: ''
      total_pages: 1460
      order: 2
      base_file: 5F7D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
