id: P007043
initial_creation_type: ocr
source_metadata:
  id: bdr:W29339
  title: བྱང་གཏེར་འདོན་ཆའི་སྐོར།
  author: ''
  volumes:
    62cb349022cb490db7882c3b4357d1e3:
      image_group_id: I1KG15264
      title: ''
      volume_number: 2
      total_pages: 1460
    07fcf77efc57439499b437197e495fb6:
      image_group_id: I5273
      title: ''
      volume_number: 1
      total_pages: 1520
ebook_metadata:
  title: བྱང་གཏེར་འདོན་ཆའི་སྐོར།
  author: ''
  sku: P007043
  cover: cover.jpg
  layers:
  - pagination
